name: continuum
channels:
  - defaults
  - conda-forge
dependencies:
  - matplotlib
  - numpy
  - numpy-base
  - pandas
  - python
  - scikit-learn
  - scipy
  - pip
  - opencv
  - tqdm
  - keras
